/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as attendanceSol from './Attendance.sol/index.js';
export type { attendanceSol };
import type * as counterSol from './Counter.sol/index.js';
export type { counterSol };
import type * as lockSol from './Lock.sol/index.js';
export type { lockSol };
export * as factories from './factories/index.js';
export type { Attendance } from './Attendance.sol/Attendance.js';
export { Attendance__factory } from './factories/Attendance.sol/Attendance__factory.js';
export type { Counter } from './Counter.sol/Counter.js';
export { Counter__factory } from './factories/Counter.sol/Counter__factory.js';
export type { Lock } from './Lock.sol/Lock.js';
export { Lock__factory } from './factories/Lock.sol/Lock__factory.js';