/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace Attendance {
      
    export type AttendanceRecordStruct = {timestamp: BigNumberish, eventId: BytesLike}

    export type AttendanceRecordStructOutput = [timestamp: bigint, eventId: string] & {timestamp: bigint, eventId: string }
  
    }

  export interface AttendanceInterface extends Interface {
    getFunction(nameOrSignature: "addOperator" | "getAttendanceRecord" | "getEventAttendees" | "hasAttended" | "markAttendance" | "operators" | "owner" | "removeOperator" | "verifyAttendance"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AttendanceMarked"): EventFragment;

    encodeFunctionData(functionFragment: 'addOperator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getAttendanceRecord', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getEventAttendees', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'hasAttended', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'markAttendance', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'operators', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeOperator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'verifyAttendance', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'addOperator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAttendanceRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEventAttendees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasAttended', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markAttendance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'operators', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeOperator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyAttendance', data: BytesLike): Result;
  }

  
    export namespace AttendanceMarkedEvent {
      export type InputTuple = [ticketId: BytesLike, eventId: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [ticketId: string, eventId: string, timestamp: bigint];
      export interface OutputObject {ticketId: string, eventId: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Attendance extends BaseContract {
    
    connect(runner?: ContractRunner | null): Attendance;
    waitForDeployment(): Promise<this>;

    interface: AttendanceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addOperator: TypedContractMethod<
      [_operator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    getAttendanceRecord: TypedContractMethod<
      [_ticketId: BytesLike, ],
      [Attendance.AttendanceRecordStructOutput],
      'view'
    >
    

    
    getEventAttendees: TypedContractMethod<
      [_eventId: BytesLike, ],
      [string[]],
      'view'
    >
    

    
    hasAttended: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    markAttendance: TypedContractMethod<
      [_ticketId: BytesLike, _eventId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    operators: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    removeOperator: TypedContractMethod<
      [_operator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    verifyAttendance: TypedContractMethod<
      [_ticketId: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addOperator'): TypedContractMethod<
      [_operator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAttendanceRecord'): TypedContractMethod<
      [_ticketId: BytesLike, ],
      [Attendance.AttendanceRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getEventAttendees'): TypedContractMethod<
      [_eventId: BytesLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'hasAttended'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'markAttendance'): TypedContractMethod<
      [_ticketId: BytesLike, _eventId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'operators'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'removeOperator'): TypedContractMethod<
      [_operator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyAttendance'): TypedContractMethod<
      [_ticketId: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'AttendanceMarked'): TypedContractEvent<AttendanceMarkedEvent.InputTuple, AttendanceMarkedEvent.OutputTuple, AttendanceMarkedEvent.OutputObject>;

    filters: {
      
      'AttendanceMarked(bytes32,bytes32,uint256)': TypedContractEvent<AttendanceMarkedEvent.InputTuple, AttendanceMarkedEvent.OutputTuple, AttendanceMarkedEvent.OutputObject>;
      AttendanceMarked: TypedContractEvent<AttendanceMarkedEvent.InputTuple, AttendanceMarkedEvent.OutputTuple, AttendanceMarkedEvent.OutputObject>;
    
    };
  }