/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as attendanceSol from './Attendance.sol/index.js';
export * as counterSol from './Counter.sol/index.js';
export * as lockSol from './Lock.sol/index.js';